[build]
functions = "/functions"
command = "npm run"
[[headers]]
  for = "/.netlify/functions/medical-forms"
  [headers.values]
     Content-Type = "application/json"
     Key = "Content-Type"
     Value = "application/json"
[[redirects]]
from = "/home"
to = "/.netlify/functions/home"

[[redirects]]
from = "/login"
to = "/.netlify/functions/login"

[[redirects]]
from = "/medical-forms"
to = "/.netlify/functions/medical-forms"

[[redirects]]
from = "/account-page"
to = "/.netlify/functions/account-page"
[[redirects]]
from = "/suggestions-page"
to = "/.netlify/functions/suggestions-page"

[[redirects]]
from = "/signup"
to = "/.netlify/functions/signup"
